<?php defined('SYSPATH') or die('No direct script access.');

//Handles Business Logic for comments
//This represents various social network connections.
class Everquest_Item extends Everquest {
	
	protected function rules() {
        return array(
            'id' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'minstatus' => [['numeric']], // smallint(5) NOT NULL DEFAULT '0',
            'Name' => [['min_length' => ['value' => 64]]], // varchar(64) NOT NULL DEFAULT '',
            'aagi' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'ac' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'accuracy' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'acha' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'adex' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'aint' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'artifactflag' => [['numeric']], // tinyint(3) unsigned NOT NULL DEFAULT '0',
            'asta' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'astr' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'attack' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'augrestrict' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'augslot1type' => [['numeric']], // tinyint(3) NOT NULL DEFAULT '0',
            'augslot1visible' => [['numeric']], // tinyint(3) DEFAULT NULL,
            'augslot2type' => [['numeric']], // tinyint(3) NOT NULL DEFAULT '0',
            'augslot2visible' => [['numeric']], // tinyint(3) DEFAULT NULL,
            'augslot3type' => [['numeric']], // tinyint(3) NOT NULL DEFAULT '0',
            'augslot3visible' => [['numeric']], // tinyint(3) DEFAULT NULL,
            'augslot4type' => [['numeric']], // tinyint(3) NOT NULL DEFAULT '0',
            'augslot4visible' => [['numeric']], // tinyint(3) DEFAULT NULL,
            'augslot5type' => [['numeric']], // tinyint(3) NOT NULL DEFAULT '0',
            'augslot5visible' => [['numeric']], // tinyint(3) DEFAULT NULL,
            'augtype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'avoidance' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'awis' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'bagsize' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'bagslots' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'bagtype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'bagwr' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'banedmgamt' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'banedmgraceamt' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'banedmgbody' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'banedmgrace' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'bardtype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'bardvalue' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'book' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'casttime' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'casttime_' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'charmfile' => [['numeric']], // varchar(32) NOT NULL DEFAULT '',
            'charmfileid' => [['numeric']], // varchar(32) NOT NULL DEFAULT '',
            'classes' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'color' => [['numeric']], // int(10) unsigned NOT NULL DEFAULT '0',
            'combateffects' => [['numeric']], // varchar(10) NOT NULL DEFAULT '',
            'extradmgskill' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'extradmgamt' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'price' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'cr' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'damage' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'damageshield' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'deity' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'delay' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'augdistiller' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'dotshielding' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'dr' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'clicktype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'clicklevel2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'elemdmgtype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'elemdmgamt' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'endur' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'factionamt1' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'factionamt2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'factionamt3' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'factionamt4' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'factionmod1' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'factionmod2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'factionmod3' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'factionmod4' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'filename' => [['numeric']], // varchar(32) NOT NULL DEFAULT '',
            'focuseffect' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'fr' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'fvnodrop' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'haste' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'clicklevel' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'hp' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'regen' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'icon' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'idfile' => [['numeric']], // varchar(30) NOT NULL DEFAULT '',
            'itemclass' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'itemtype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'ldonprice' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'ldontheme' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'ldonsold' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'light' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'lore' => [['numeric']], // varchar(80) NOT NULL DEFAULT '',
            'loregroup' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'magic' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'mana' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'manaregen' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'enduranceregen' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'material' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'maxcharges' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'mr' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'nodrop' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'norent' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'pendingloreflag' => [['numeric']], // tinyint(3) unsigned NOT NULL DEFAULT '0',
            'pr' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'procrate' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'races' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'range' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'reclevel' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'recskill' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'reqlevel' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'sellrate' => [['numeric']], // float NOT NULL DEFAULT '0',
            'shielding' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'size' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'skillmodtype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'skillmodvalue' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'slots' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'clickeffect' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'spellshield' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'strikethrough' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'stunresist' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'summonedflag' => [['numeric']], // tinyint(3) unsigned NOT NULL DEFAULT '0',
            'tradeskills' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'favor' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'weight' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK012' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK013' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'benefitflag' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK054' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK059' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'booktype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'recastdelay' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'recasttype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'guildfavor' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK123' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK124' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'attuneable' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'nopet' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'updated' => [['numeric']], // datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
            'comment' => [['numeric']], // varchar(255) NOT NULL DEFAULT '',
            'UNK127' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'pointtype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'potionbelt' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'potionbeltslots' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'stacksize' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'notransfer' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'stackable' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK134' => [['numeric']], // varchar(255) NOT NULL DEFAULT '',
            'UNK137' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'proceffect' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'proctype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'proclevel2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'proclevel' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK142' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'worneffect' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'worntype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'wornlevel2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'wornlevel' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK147' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'focustype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'focuslevel2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'focuslevel' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK152' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'scrolleffect' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'scrolltype' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'scrolllevel2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'scrolllevel' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK157' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'serialized' => [['numeric']], // datetime DEFAULT NULL,
            'verified' => [['numeric']], // datetime DEFAULT NULL,
            'serialization' => [['numeric']], // text,
            'source' => [['numeric']], // varchar(20) NOT NULL DEFAULT '',
            'UNK033' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'lorefile' => [['numeric']], // varchar(32) NOT NULL DEFAULT '',
            'UNK014' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'svcorruption' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK038' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK060' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'augslot1unk2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'augslot2unk2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'augslot3unk2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'augslot4unk2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'augslot5unk2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK120' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK121' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'questitemflag' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK132' => [['numeric']], // text NOT NULL,
            'clickunk5' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'clickunk6' => [['numeric']], // varchar(32) NOT NULL DEFAULT '',
            'clickunk7' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'procunk1' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'procunk2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'procunk3' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'procunk4' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'procunk6' => [['numeric']], // varchar(32) NOT NULL DEFAULT '',
            'procunk7' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'wornunk1' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'wornunk2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'wornunk3' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'wornunk4' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'wornunk5' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'wornunk6' => [['numeric']], // varchar(32) NOT NULL DEFAULT '',
            'wornunk7' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'focusunk1' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'focusunk2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'focusunk3' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'focusunk4' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'focusunk5' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'focusunk6' => [['numeric']], // varchar(32) NOT NULL DEFAULT '',
            'focusunk7' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'scrollunk1' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'scrollunk2' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'scrollunk3' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'scrollunk4' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'scrollunk5' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'scrollunk6' => [['numeric']], // varchar(32) NOT NULL DEFAULT '',
            'scrollunk7' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK193' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'purity' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'evolvinglevel' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'clickname' => [['numeric']], // varchar(64) NOT NULL DEFAULT '',
            'procname' => [['numeric']], // varchar(64) NOT NULL DEFAULT '',
            'wornname' => [['numeric']], // varchar(64) NOT NULL DEFAULT '',
            'focusname' => [['numeric']], // varchar(64) NOT NULL DEFAULT '',
            'scrollname' => [['numeric']], // varchar(64) NOT NULL DEFAULT '',
            'dsmitigation' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_str' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_int' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_wis' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_agi' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_dex' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_sta' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_cha' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_pr' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_dr' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_fr' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_cr' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_mr' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'heroic_svcorrup' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'healamt' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'spelldmg' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'clairvoyance' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'backstabdmg' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'created' => [['numeric']], // varchar(64) NOT NULL DEFAULT '',
            'elitematerial' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'ldonsellbackrate' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'scriptfileid' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'expendablearrow' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'powersourcecapacity' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'bardeffect' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'bardeffecttype' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'bardlevel2' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'bardlevel' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'bardunk1' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'bardunk2' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'bardunk3' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'bardunk4' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'bardunk5' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'bardname' => [['numeric']], // varchar(64) NOT NULL DEFAULT '',
            'bardunk7' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'UNK214' => [['numeric']], // smallint(6) NOT NULL DEFAULT '0',
            'UNK219' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK220' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK221' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK222' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK223' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK224' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK225' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK226' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK227' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK228' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK229' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK230' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK231' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK232' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK233' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK234' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK235' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK236' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK237' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK238' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK239' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK240' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK241' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
            'UNK242' => [['numeric']], // int(11) NOT NULL DEFAULT '0',
        );
	}

    public function find_all_by_name($itemName, $limit = 10, $offset = 0) {

        $items = DB::select()->from('items')->where('items.name', 'LIKE', "%$itemName%")
        ->limit($limit)
        ->offset($offset)
        ->as_object()->execute()->as_array();
        return $items;
    }

    public function find_total_by_name($itemName) {

        $total = DB::select('count(*)')->from('items')->where('items.name', 'LIKE', "%$itemName%")
        ->execute()->get('count(*)');
        return $total;
    }

    public function get_by_item_id($itemID) {
      $item = DB::select()->from('items')->where('items.id', '=', $itemID)->limit(1)->execute()->current();
      return $item;
    }
}
