// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rebuildeq.proto

package eqproto

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type User struct {
	AccountId            int64    `protobuf:"varint,1,opt,name=account_id,json=accountId,proto3" json:"account_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_rebuildeq_ff7e790ef9bc891b, []int{0}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetAccountId() int64 {
	if m != nil {
		return m.AccountId
	}
	return 0
}

type Build struct {
	Hash                 string   `protobuf:"bytes,1,opt,name=hash,proto3" json:"hash,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Build) Reset()         { *m = Build{} }
func (m *Build) String() string { return proto.CompactTextString(m) }
func (*Build) ProtoMessage()    {}
func (*Build) Descriptor() ([]byte, []int) {
	return fileDescriptor_rebuildeq_ff7e790ef9bc891b, []int{1}
}
func (m *Build) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Build.Unmarshal(m, b)
}
func (m *Build) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Build.Marshal(b, m, deterministic)
}
func (dst *Build) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Build.Merge(dst, src)
}
func (m *Build) XXX_Size() int {
	return xxx_messageInfo_Build.Size(m)
}
func (m *Build) XXX_DiscardUnknown() {
	xxx_messageInfo_Build.DiscardUnknown(m)
}

var xxx_messageInfo_Build proto.InternalMessageInfo

func (m *Build) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

type Builds struct {
	Builds               []*Build `protobuf:"bytes,1,rep,name=builds,proto3" json:"builds,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Builds) Reset()         { *m = Builds{} }
func (m *Builds) String() string { return proto.CompactTextString(m) }
func (*Builds) ProtoMessage()    {}
func (*Builds) Descriptor() ([]byte, []int) {
	return fileDescriptor_rebuildeq_ff7e790ef9bc891b, []int{2}
}
func (m *Builds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Builds.Unmarshal(m, b)
}
func (m *Builds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Builds.Marshal(b, m, deterministic)
}
func (dst *Builds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Builds.Merge(dst, src)
}
func (m *Builds) XXX_Size() int {
	return xxx_messageInfo_Builds.Size(m)
}
func (m *Builds) XXX_DiscardUnknown() {
	xxx_messageInfo_Builds.DiscardUnknown(m)
}

var xxx_messageInfo_Builds proto.InternalMessageInfo

func (m *Builds) GetBuilds() []*Build {
	if m != nil {
		return m.Builds
	}
	return nil
}

type Page struct {
	Offset               int64    `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	Limit                int64    `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Total                int64    `protobuf:"varint,3,opt,name=total,proto3" json:"total,omitempty"`
	OrderBy              int64    `protobuf:"varint,4,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	IsDescending         int64    `protobuf:"varint,5,opt,name=is_descending,json=isDescending,proto3" json:"is_descending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Page) Reset()         { *m = Page{} }
func (m *Page) String() string { return proto.CompactTextString(m) }
func (*Page) ProtoMessage()    {}
func (*Page) Descriptor() ([]byte, []int) {
	return fileDescriptor_rebuildeq_ff7e790ef9bc891b, []int{3}
}
func (m *Page) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Page.Unmarshal(m, b)
}
func (m *Page) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Page.Marshal(b, m, deterministic)
}
func (dst *Page) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Page.Merge(dst, src)
}
func (m *Page) XXX_Size() int {
	return xxx_messageInfo_Page.Size(m)
}
func (m *Page) XXX_DiscardUnknown() {
	xxx_messageInfo_Page.DiscardUnknown(m)
}

var xxx_messageInfo_Page proto.InternalMessageInfo

func (m *Page) GetOffset() int64 {
	if m != nil {
		return m.Offset
	}
	return 0
}

func (m *Page) GetLimit() int64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *Page) GetTotal() int64 {
	if m != nil {
		return m.Total
	}
	return 0
}

func (m *Page) GetOrderBy() int64 {
	if m != nil {
		return m.OrderBy
	}
	return 0
}

func (m *Page) GetIsDescending() int64 {
	if m != nil {
		return m.IsDescending
	}
	return 0
}

type Pages struct {
	Pages                []*Page  `protobuf:"bytes,1,rep,name=pages,proto3" json:"pages,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Pages) Reset()         { *m = Pages{} }
func (m *Pages) String() string { return proto.CompactTextString(m) }
func (*Pages) ProtoMessage()    {}
func (*Pages) Descriptor() ([]byte, []int) {
	return fileDescriptor_rebuildeq_ff7e790ef9bc891b, []int{4}
}
func (m *Pages) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Pages.Unmarshal(m, b)
}
func (m *Pages) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Pages.Marshal(b, m, deterministic)
}
func (dst *Pages) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Pages.Merge(dst, src)
}
func (m *Pages) XXX_Size() int {
	return xxx_messageInfo_Pages.Size(m)
}
func (m *Pages) XXX_DiscardUnknown() {
	xxx_messageInfo_Pages.DiscardUnknown(m)
}

var xxx_messageInfo_Pages proto.InternalMessageInfo

func (m *Pages) GetPages() []*Page {
	if m != nil {
		return m.Pages
	}
	return nil
}

func init() {
	proto.RegisterType((*User)(nil), "eqproto.User")
	proto.RegisterType((*Build)(nil), "eqproto.Build")
	proto.RegisterType((*Builds)(nil), "eqproto.Builds")
	proto.RegisterType((*Page)(nil), "eqproto.Page")
	proto.RegisterType((*Pages)(nil), "eqproto.Pages")
}

func init() { proto.RegisterFile("rebuildeq.proto", fileDescriptor_rebuildeq_ff7e790ef9bc891b) }

var fileDescriptor_rebuildeq_ff7e790ef9bc891b = []byte{
	// 253 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x3c, 0x8e, 0x51, 0x4b, 0xc3, 0x30,
	0x14, 0x85, 0x89, 0x6b, 0x3a, 0x77, 0x75, 0x0a, 0x17, 0x91, 0x88, 0x08, 0x23, 0x43, 0xd9, 0x83,
	0x14, 0xd1, 0x7f, 0x50, 0x7c, 0xd0, 0x37, 0x29, 0xf8, 0x5c, 0xda, 0x26, 0xdb, 0x02, 0xb5, 0xd9,
	0x92, 0xec, 0x61, 0x7f, 0xc1, 0x5f, 0xec, 0xa3, 0xe4, 0x36, 0xec, 0xed, 0x9c, 0xf3, 0x5d, 0xee,
	0x39, 0x70, 0xed, 0x74, 0x7b, 0x30, 0xbd, 0xd2, 0xfb, 0x62, 0xe7, 0x6c, 0xb0, 0x38, 0xd5, 0x7b,
	0x12, 0xf2, 0x11, 0xb2, 0x6f, 0xaf, 0x1d, 0x3e, 0x00, 0x34, 0x5d, 0x67, 0x0f, 0x43, 0xa8, 0x8d,
	0x12, 0x6c, 0xc1, 0x56, 0x93, 0x6a, 0x96, 0x92, 0x4f, 0x25, 0xef, 0x81, 0x97, 0xf1, 0x01, 0x22,
	0x64, 0xdb, 0xc6, 0x6f, 0xe9, 0x62, 0x56, 0x91, 0x96, 0x2f, 0x90, 0x13, 0xf4, 0xf8, 0x04, 0x39,
	0xf5, 0x78, 0xc1, 0x16, 0x93, 0xd5, 0xc5, 0xeb, 0x55, 0x91, 0x7a, 0x0a, 0x3a, 0xa8, 0x12, 0x95,
	0xbf, 0x0c, 0xb2, 0xaf, 0x66, 0xa3, 0xf1, 0x16, 0x72, 0xbb, 0x5e, 0x7b, 0x1d, 0x52, 0x65, 0x72,
	0x78, 0x03, 0xbc, 0x37, 0x3f, 0x26, 0x88, 0x33, 0x8a, 0x47, 0x13, 0xd3, 0x60, 0x43, 0xd3, 0x8b,
	0xc9, 0x98, 0x92, 0xc1, 0x3b, 0x38, 0xb7, 0x4e, 0x69, 0x57, 0xb7, 0x47, 0x91, 0x11, 0x98, 0x92,
	0x2f, 0x8f, 0xb8, 0x84, 0xb9, 0xf1, 0xb5, 0xd2, 0xbe, 0xd3, 0x83, 0x32, 0xc3, 0x46, 0x70, 0xe2,
	0x97, 0xc6, 0xbf, 0x9f, 0x32, 0xf9, 0x0c, 0x3c, 0x6e, 0xf1, 0xb8, 0x04, 0xbe, 0x8b, 0x22, 0x8d,
	0x9f, 0x9f, 0xc6, 0x47, 0x5c, 0x8d, 0xac, 0xe4, 0x1f, 0xec, 0x8f, 0xb1, 0x36, 0x27, 0xf2, 0xf6,
	0x1f, 0x00, 0x00, 0xff, 0xff, 0x9c, 0x57, 0x63, 0xd4, 0x5a, 0x01, 0x00, 0x00,
}
