/*
 * RebuildEQ API
 *
 * RebuildEQ API
 *
 * API version: 1.0.0
 * Contact: rebuildeq@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Changelog struct {

	Title string `json:"title,omitempty"`

	// Date the change applied
	Date string `json:"date,omitempty"`
}
