/*
 * RebuildEQ API
 *
 * RebuildEQ API
 *
 * API version: 1.0.0
 * Contact: rebuildeq@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Changelog struct {

	Id int32 `json:"id,omitempty"`

	Title string `json:"title,omitempty"`

	Body string `json:"body,omitempty"`

	// Date the change applied
	Date string `json:"date,omitempty"`
}
