/*
 * RebuildEQ API
 *
 * RebuildEQ API
 *
 * API version: 1.0.0
 * Contact: rebuildeq@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Character struct {

	// class ID representing character, e.g. 1 = warrior
	ClassId int32 `json:"classId,omitempty"`

	Name string `json:"name,omitempty"`

	Id int32 `json:"id,omitempty"`

	Zoneid int32 `json:"zoneid,omitempty"`
}
