/*
 * RebuildEQ API
 *
 * RebuildEQ API
 *
 * API version: 1.0.0
 * Contact: rebuildeq@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Item struct {

	Name string `json:"name,omitempty"`

	Id int32 `json:"id,omitempty"`

	// Icon to display for art reasons
	Icon int32 `json:"icon,omitempty"`

	// Used by inventory, which slot the item is at
	Slot int32 `json:"slot,omitempty"`

	// Used by inventory, how many charges of the item
	Charges int32 `json:"charges,omitempty"`
}
