/*
 * RebuildEQ API
 *
 * RebuildEQ API
 *
 * API version: 1.0.0
 * Contact: rebuildeq@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type LootTableEntry struct {

	LootDrops []LootDropEntry `json:"lootDrops,omitempty"`

	Probability int32 `json:"probability,omitempty"`

	LootTableId int32 `json:"lootTableId,omitempty"`
}
