/*
 * RebuildEQ API
 *
 * RebuildEQ API
 *
 * API version: 1.0.0
 * Contact: rebuildeq@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type LootDropEntry struct {

	LootDropId int32 `json:"lootDropId,omitempty"`

	ItemId int32 `json:"itemId,omitempty"`

	ItemName string `json:"itemName,omitempty"`

	ItemCharges int32 `json:"itemCharges,omitempty"`

	Chance float32 `json:"chance,omitempty"`
}
