/*
 * RebuildEQ API
 *
 * RebuildEQ API
 *
 * API version: 1.0.0
 * Contact: rebuildeq@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type SpawnEntry struct {

	// 50 is 50% chance
	Chance int32 `json:"chance,omitempty"`

	// number of seconds for mob to respawn
	RespawnTime int32 `json:"respawnTime,omitempty"`

	// variance is a randomizer to make respawn less predictable
	Variance int32 `json:"variance,omitempty"`

	X float32 `json:"x,omitempty"`

	Y float32 `json:"y,omitempty"`

	Z float32 `json:"z,omitempty"`

	ZoneName string `json:"zoneName,omitempty"`

	ZoneShortName string `json:"zoneShortName,omitempty"`

	ZoneId int32 `json:"zoneId,omitempty"`
}
