/*
 * RebuildEQ API
 *
 * RebuildEQ API
 *
 * API version: 1.0.0
 * Contact: rebuildeq@gmail.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package client

type Zone struct {

	Name string `json:"name,omitempty"`

	Shortname string `json:"shortname,omitempty"`

	Id int32 `json:"id,omitempty"`

	// a bitwise number representing level ranges
	Levels int32 `json:"levels,omitempty"`
}
